const data = [
  {
    id: 1,
    image: "./images/prod1.png",
    title: "Bola Penalty",
    price: 125.0,
    quantity: 1,
  },
  {
    id: 2,
    image: "./images/prod2.png",
    title: "Joelheiras Allsix",
    price: 69.0,
    quantity: 1,
  },
  {
    id: 3,
    image: "./images/prod3.png",
    title: "Joelheiras Allsix Premium",
    price: 79.0,
    quantity: 1,
  },
  {
    id: 4,
    image: "./images/prod4.png",
    title: "Manguito Longo",
    price: 59.0,
    quantity: 1,
  },
  {
    id: 5,
    image: "./images/prod5.png",
    title: "Manguito Curto",
    price: 49.0,
    quantity: 1,
  },
  {
    id: 6,
    image: "./images/prod6.png",
    title: "Rede 10m Simples",
    price: 199.0,
    quantity: 1,
  },
  {
    id: 7,
    image: "./images/prod7.png",
    title: "Rede 10m Profissional",
    price: 249.0,
    quantity: 1,
  },
  {
    id: 8,
    image: "./images/prod8.png",
    title: "Bola Mikasa VSO 2000",
    price: 149.0,
    quantity: 1,
  },
  {
    id: 9,
    image: "./images/prod9.png",
    title: "Bola Mikasa Pró",
    price: 199.0,
    quantity: 1,
  },
  {
    id: 10,
    image: "./images/prod10.png",
    title: "Tênis Asics Sky Elite",
    price: 229.0,
    quantity: 1,
  },
  {
    id: 11,
    image: "./images/prod11.png",
    title: "Tênis Asics Blue",
    price: 219.0,
    quantity: 1,
  },
  {
    id: 12,
    image: "./images/prod12.png",
    title: "Tênis Asics Pink",
    price: 219.0,
    quantity: 1,
  },
  {
    id: 13,
    image: "./images/prod13.png",
    title: "Tênis Nike Black and Pink",
    price: 200.5,
    quantity: 1,
  },
  {
    id: 14,
    image: "./images/prod14.png",
    title: "Camiseta Esportiva Azul",
    price: 79.0,
    quantity: 1,
  },
  {
    id: 15,
    image: "./images/prod15.png",
    title: "Camiseta Regata Rosa",
    price: 65.0,
    quantity: 1,
  },
  {
    id: 16,
    image: "./images/prod16.png",
    title: "Camiseta Regata Preta",
    price: 55.0,
    quantity: 1,
  },
];

export default data;
